name: Build and Test
on:
  pull_request:
    paths:
      - '**.js'
      - '**.ts'
      - '**.tsx'
      - '**.json'
      - 'yarn.lock'
      - 'build-test.yaml'
  push:
    branches:
      - 'main'
      - 'master'

# Kill the workflow if the PR is updated with a new commit
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node
        uses: actions/setup-node@v3

      - name: Test
        run: yarn test
        shell: bash
